version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  app:
    container_name: app
    image:  openjdk:17-jdk-slim
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    working_dir: /app
    command: [ "./gradlew", "bootrun"]
    restart: always
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - db
  db:
    image: mariadb:10
    ports:
      - 3307:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    env_file: .env
    environment:
      TZ: Asia/Seoul
    restart: always