version: "3"
services:
  app:
    container_name: app
    image:  openjdk:17-jdk-slim
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: [ "./gradlew", "bootrun"]
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"